name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    uses: teh-hippo/common-repo-configs/.github/workflows/release-please.yml@53d1fc8ee012e7fba482104fdb2d779eff892348  # v3.2.14
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
