name: Release Please

on:
  push:
    branches: [main]

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    uses: teh-hippo/common-repo-configs/.github/workflows/release-please.yml@2a1423750ab58fdbe2ce21d35f583f07c79fcdc8  # v2.0.3
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
