name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    uses: teh-hippo/common-repo-configs/.github/workflows/release-please.yml@f4be12d62c57181f39424bf4ff8460141ed43649  # v3.2.15
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
